app/urls.py
# """app URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('playground/', include('playground.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('store/', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playground/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.say_hello)
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('all_products', views.all_products, name='all_products'),
    path('home', views.home),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('change/<int:id>/', views.change_product, name='change_product'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
]

playground/models.py
from django.db import models

# Create your models here.

store/models.py
from contextlib import nullcontext
from distutils.command.upload import upload
from turtle import title
from unicodedata import category
from unittest.util import _MAX_LENGTH
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from base64 import b64encode
from django import template
register = template.Library()

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    image_bin = models.BinaryField(null=True, blank=True, default=None)
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=6)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    time_to_read = models.CharField(max_length=64, default='очень очень долго')
    id = models.Model.pk

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    @register.filter
    def img(self):
        return b64encode(self.image_bin).decode('utf-8')

    def get_slug(self):
        return self.slug

    def get_id(self):
        return self.id

store/forms.py
from django import forms

from .models import Product, Category

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs.update(
            {"class": "form-control mb-2 product-form", "placeholder": "title"}
        )

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ["id"]
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

playground/views.py
from django.shortcuts import render
from django.http import HttpResponse

def say_hello(request):
    return render (request, 'hello.html',{'name':'Vladlena'})

store/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
from .forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect


def all_products(request):
    products = Product.objects.all()
    return render(request, 'store/home.html', {'products': products})


def home(request):
    return render(request, 'store/home.html')


def categories(request):
    return{
        'categories':Category.objects.all()
    }

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'Products/detail.html', {'product': product})

def change_product(request, id):
    if request.method == "POST":
        product = Product.objects.get(id=id)
        product_form = ProductForm(instance=product, data=request.POST)
        if product_form.is_valid():
            product_form.save()
            return render(request, 'Products/change_product.html', {'product': product})
    else:
        product = Product.objects.get(id=id)
    return render(request, 'Products/change_product.html', {'product': product})

def delete_product(request, id):
    product = Product.objects.get(id=id)
    print(product.title)
    product.delete()
    return all_products(request)

playground/templates/Goodby.html
{%include 'navbar.html' %}
<html>
    <body>
        {% if name %}
        <h1>Goodby {{name}}</h1>
        {% else %}
        <h1>Hello World</h1>
        {% endif %}
    </body>
</html>

playground/templates/hello.html
{%include 'navbar.html' %}
<html>
    <body>
        {% if name %}
        <h1>Hello {{name}}</h1>
        {% else %}
        <h1>Hello World</h1>
        {% endif %}
    </body>
</html>

playground/templates/navbar.html
<a href="/">
    <h1>LOGO</h1>
</a>
<hr>

templates/Products/change_product.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="col-6 mx-auto">
  <h1 class="h3">Изменить продукт</h1>
  <div>Измените название <b>цену</b> и описание продукта</div>
  <hr />
  <form name="product_prop" class="product-form" method="POST" enctype="multipart/form-data">
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
      Error: Please try again!
    </div>
    {% endif %}
    {% csrf_token %}
    <input class="card-text m-0" name="title" value="{{ product.title }}">
    <div style="display:inline-flex">
      <input class="btn btn-danger btn-block py-2 mb-4 mt-4 fw-bold w-100" style="margin-right: 1.5rem!important;" type="button" onclick="location.href='../../delete/{{product.id}}'" value="Удалить" />
    <button class="btn btn-primary btn-block py-2 mb-4 mt-4 fw-bold w-100" type="button" value="Submit" onclick="submitForm()">
    Сохранить
    </button></div>
  </form>

</div>

<script>

function submitForm() {
   console.log("test0")
   var form = document.getElementsByName('product_prop')[0];
   console.log("test1")
   form.submit(); // Submit the form
   return false; // Prevent page refresh
}
</script>
{% endblock %}






<!--{% block sub_content %}-->

<!--  <div class="col-12">-->
<!--    <h1 class="h2">Your Account</h1>-->
<!--  </div>-->
<!--  <div class="col-12 d-flex justify-content-between">-->
<!--    <div>Manage your <b>orders</b> and personal details</div>-->
<!--    {% comment %} <div><a href="{% url "account:edit_details" %}">Change Details</a></div> {% endcomment %}-->
<!--  </div>-->
<!--  <hr />-->

<!--  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">-->
<!--    <div class="col">-->
<!--      <a href="#" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">-->
<!--      <div class="card mb-3">-->
<!--        <div class="row g-0">-->
<!--          <div class="col-2 position-relative">-->
<!--            <svg class="position-absolute top-50 start-50 translate-middle" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-gift"-->
<!--              viewBox="0 0 16 16">-->
<!--              <path-->
<!--                d="M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 14.5V7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zM1 4v2h6V4H1zm8 0v2h6V4H9zm5 3H9v8h4.5a.5.5 0 0 0 .5-.5V7zm-7 8V7H2v7.5a.5.5 0 0 0 .5.5H7z" />-->
<!--            </svg>-->
<!--          </div>-->
<!--          <div class="col-10">-->
<!--            <div class="card-body ps-0 ps-md-1">-->
<!--              <h1 class="h5">Orders</h1>-->
<!--              <p class="card-text small text-muted">View, Track, Change or buy again</p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="col">-->
<!--      <a href="{% url "account:edit_details" %}" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">-->
<!--      <div class="card mb-3">-->
<!--        <div class="row g-0">-->
<!--          <div class="col-2 position-relative">-->
<!--            <svg class="position-absolute top-50 start-50 translate-middle" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-shield-lock" viewBox="0 0 16 16">-->
<!--              <path d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z"/>-->
<!--              <path d="M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z"/>-->
<!--            </svg>-->
<!--          </div>-->
<!--          <div class="col-10">-->
<!--            <div class="card-body ps-0 ps-md-1">-->
<!--              <h1 class="h5">Login & Security</h1>-->
<!--              <p class="card-text small text-muted">Edit login, email and phone number</p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--      </a>-->
<!--    </div>-->
<!--    <div class="col">-->
<!--      <a href="{% url "account:addresses" %}" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">-->
<!--      <div class="card mb-3">-->
<!--        <div class="row g-0">-->
<!--          <div class="col-2 position-relative">-->
<!--            <svg class="position-absolute top-50 start-50 translate-middle" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">-->
<!--              <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>-->
<!--            </svg>-->
<!--          </div>-->
<!--          <div class="col-10">-->
<!--            <div class="card-body ps-0 ps-md-1">-->
<!--              <h1 class="h5">Your Addresses</h1>-->
<!--              <p class="card-text small text-muted">Edit your shipping addresses</p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--      </a>-->
<!--    </div>-->

<!--  </div>-->

<!--{% endblock %}-->

templates/Products/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Автор)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">В твёрдом переплёте</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} руб.</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
<!--                               <label for="select">Количество</label>-->
<!--                                <select id="select">-->
<!--                                   <option value="">1</option>-->
<!--                                    <option value="">2</option>-->
<!--                                    <option value="">3</option>-->
<!--                                    <option value="">4</option>-->
                                </select>

                            </div>
                            <div class="col-6 text-end">
                                <button type="button" id="change-button" class="btn btn-secondary btn-sm">
                                     <a href="../change/{{ product.get_id }}">Изменить</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
{% endblock %}

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <title>{% block title %} My shop {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
            crossorigin="anonymous"
    />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Магазин</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Главна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Ссылки</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Категории
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:all_products" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %} >
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Например: Игрушки" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

    <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
            integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
            crossorigin="anonymous"
    ></script>

templates/store/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-3 text-center container">
    <div class="row py-lg-1">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold">Тут название магазина</h1>
        <p class="lead text-muted">А тут описание того, что там продается</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Создать аккаунт (не кликабельно)</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">Все товары</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_slug }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ product.time_to_read }}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}